##### 线性回归的简单实现

In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train=True):   #@save
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [4]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [5]:
next(iter(data_iter))

[tensor([[-1.0429, -0.2743],
         [-0.1173, -0.5340],
         [-2.2094, -0.1514],
         [-1.5803,  1.5665],
         [ 0.9567,  0.8740],
         [-1.2856, -0.8956],
         [-1.6272,  0.4103],
         [ 0.5178, -1.1106],
         [ 0.3753,  0.1378],
         [-0.9679, -0.5336]]),
 tensor([[ 3.0510],
         [ 5.7843],
         [ 0.3011],
         [-4.2819],
         [ 3.1445],
         [ 4.6708],
         [-0.4483],
         [ 9.0028],
         [ 4.4816],
         [ 4.0829]])]

In [6]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

In [7]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [8]:
loss = nn.MSELoss()

In [9]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [10]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000158
epoch 2, loss 0.000101
epoch 3, loss 0.000101


In [11]:
w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)

w的估计误差： tensor([-0.0002, -0.0004])
b的估计误差： tensor([-0.0006])


In [13]:
# 显示梯度
print(net[0].weight.grad)

tensor([[-0.0030, -0.0042]])
